apiVersion: asset.sap/v1
kind: Asset
metadata:
  name: n8n
  version: "1.0.0"
type: n8n-workflow
sourceRoot: "workflows"
provides:
  workflows:
    - definitionFile: bupa-sync-orchestration.n8n.json
      name: bupa-sync-orchestration
